server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /yn


spring:
  profiles:
    active: test

  thymeleaf:
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  aop:
    proxy-target-class: true

mybatis-plus:
  # 实体类扫描路径
  type-aliases-package: com.picc.*.entity
  # xml 扫描路径
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
    #实体驼峰是否映射下划线_
    map-underscore-to-camel-case: false
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false